### ISSUE TITLE
Cookies issue

### ISSUE THREAD

**Issue by ranahaani** [ykutaykuta/youtube-upload-scripts#1]
Hey Man, Thanks for this beautiful solution, this was working fine on my system, but recently I am getting this popup, it works on a normal chrome browser but didn't work on selenium. I updated my cookies many times, but it didn't work. I am getting cookies using [https://www.editthiscookie.com/](https://www.editthiscookie.com/ )
Do you have any idea? how can I get rid of this?
![image](https://user-images.githubusercontent.com/28961554/147100055-e6880836-35c3-499f-b288-da97df5b8942.png)

**Comment by ykutaykuta** [comment]
To export cookie, using the follow chrome extension

![image](https://user-images.githubusercontent.com/47108176/155825296-f105c458-ea14-4427-b1d5-1a0544d1132e.png)
